### ISSUE TITLE
How to wait until self.ip is populated

### ISSUE THREAD

**Issue by tvishwanatharkin** [terraform-providers/terraform-provider-vcd#267]
Hi there,

I am trying to create vApps in vcd using terraform provider.
I intend to use DHCP assigned IP and later modify the network using provisioner. I have few questions
1) DHCP takes some time to assign IP to VMs. So, the self.ip variable is not populated until I run terraform refresh. Because self.ip is not populated, I can't run the remote-exec provisioner.

2) Is there a better way to provision vApps with VMs having static ips? Because, though I used the MANUAL allocation with IP set, the changes were effected only at the VCD level but the VM actually was running on some other IP.

### Terraform Version
0.12.1
vcd provider version - v2.3.0

### Affected Resource(s)
- vcd_vapp_vm
- vcd_vapp

If this issue appears to affect multiple resources, it may be an issue with Terraform's core, so please mention this.

### Terraform Configuration Files
```variable "oc_user" {}
variable "oc_password" {}
variable "oc_org" {}
variable "oc_url" {}
variable "oc_vdc" {}
variable "oc_ignore_ssl" {}

variable "vapp_name" {
  type = string
  description = "Name of the vApp which will be created"
}
/*variable "slave_names" {
	type = string
  description = "A comma separated string with slave names. vApp will contain as many number of VMs as the number of names passed here"
}*/
variable "static_ips" {
  type = string
  description =<<-DESC
  Comma separated string with static_ips that will be assigned after provisioning.
  vApp will contain as many number of VMs as the number of ip addresses passed.
  Slaves will be named based on the ip address. Ex: slave33,slave32
  DESC
}
variable "vm_cpu" {
  type = number
  description = "Number cpus"
  default = 4
}
variable "vm_memory" {
  type = number
  description = "VM Memory to be allocated in MB"
  default = 32768
}

locals {
  s_ips = [for s in split(",", var.static_ips) : trimspace(s)]
  // Generate slave names from the last bit of ip address
  s_names = [for ip in local.s_ips : "slave${split(".", ip)[3]}"]
}

provider "vcd" {
  user      = "${var.oc_user}"
  password  = "${var.oc_password}"
  org       = "${var.oc_org}"
  url       = "${var.oc_url}"
  vdc       = "${var.oc_vdc}"
  allow_unverified_ssl  = "${var.oc_ignore_ssl}"
  max_retry_timeout = "240"
 }

 resource "vcd_vapp" "jenkins_vapp" { 
  name          = "${var.vapp_name}"
  power_on      = "true"
}

resource "vcd_vapp_vm" "jenkins_slave" {
  // Looping variable to create vApps
  count         = "${length(local.s_ips)}"
  
  vapp_name     = "${vcd_vapp.jenkins_vapp.name}"
  name          = "${local.s_names[count.index]}"
  catalog_name  = "BASE_TEMPLATES"
  template_name = "UBUNTU_BASE_16046_1TB"
  memory        = "${var.vm_memory}"
  cpus          = "${var.vm_cpu}"
  
  metadata = {
      role    = "jenkins_slave"
      name    = "${local.s_names[count.index]}"
      vapp    = "${vcd_vapp.jenkins_vapp.name}"
    }
  
  network {
    type               = "org"
    name               = "net_name"
    ip_allocation_mode = "DHCP"
    #ip                 = "${local.s_ips[count.index]}"
    is_primary         = true
  }
  power_on      = true
  
  provisioner "remote-exec" {
    connection {
      type = "ssh"
      host = "${self.ip}"
      user = "ubuntu"
      password = "ubuntu"
    }
    inline = [
      "sudo apt-get update",
      "touch tarakesh.txt"
    ]
  }
}
```

### Expected Behavior
What should have happened?
self.ip should return DHCP assigned IP Address
### Actual Behavior
What actually happened?
Since self.ip is not populated, the provisioner block always fails.
I am not able to perform a terraform refresh from within terraform script.

### Steps to Reproduce
Please list the steps required to reproduce the issue, for example:
1. `terraform apply`

### Important Factoids
Are there anything atypical about your accounts that we should know? For example: Running in EC2 Classic? Custom version of OpenStack? Tight ACLs?

### References
Are there any other GitHub issues (open or closed) or Pull Requests that should be linked here? For example:
- GH-1234

**Comment by lvirbalas** [comment]
> Because, though I used the MANUAL allocation with IP set, the changes were effected only at the VCD level but the VM actually was running on some other IP.

Setting IP address with `ip_allocation_mode = MANUAL` is the way to go. What OVA are you using? Does it have VMware Tools installed? You may be hitting an issue that operating system in the OVA is not responding to the IP address assignment due to lack of VMware Tools.

Please try deploying Photon OS, which is sure to work, to check whether this is the issue with OVA or something else:
https://github.com/vmware/photon/wiki/Downloading-Photon-OS
Specific OVA which I used lately:
http://dl.bintray.com/vmware/photon/3.0/GA/ova/photon-hw11-3.0-26156e2.ova

I'll let @Didainius cover the first question.

**Comment by tvishwanatharkin** [comment]
@lvirbalas vmware tools is installed in the vapp template.
I am using a Ubuntu 16.04.6 template
vmware tools version - 1.2.0.1608

**Comment by tvishwanatharkin** [comment]
@lvirbalas The static IP is being applied to the VM now. I had to recreate the template with "Enable Guest Customization" selected. 
Is there a way we can achieve a reboot of vms from within remote-exec provisioner?

**Comment by Didainius** [comment]
@tvishwanatharkin,
Sorry for being a bit late but wasn't online for a few days. Some replies and a general comment below.

> Another point is that self.ip will never resolve to IP in vcd provider 2.3. We have to use interpolation as below
> `host = "${self.network.0.ip}"`

Yes. Because the `self.ip` is the legacy way for assigning IPs because of it's limitation for only one network card. It used to be buggy, we tuned it up, but plan to remove it later (probably at 3.0) and leave only the `network` blocks because of it's ability to cover both simple and complicated scenarios (multiple network cards).

>     1. DHCP takes some time to assign IP to VMs. So, the self.ip variable is not populated until I run terraform refresh. Because self.ip is not populated, I can't run the remote-exec provisioner.

As I mentioned above I'd recommend using the network block and still DHCP is problematic (see below).

In general we've seen that DHCP is not that straight forward as it does not report the IP that quickly to vCD therefore Terraform can't do any better here. It sounds to me as to cover your case `ip_allocation_mode=POOL` would be the most convenient way to use it. You would always get the IP timely and could access the VMs (provided your Guest OS is able to set the IPs using tools)

**Comment by Didainius** [comment]
I’ closing this now. Feel free to reopen if needed.
