### ISSUE TITLE
Add support for VM disk management in vcd_vapp_vm resource

### ISSUE THREAD

**Issue by Didainius** [terraform-providers/terraform-provider-vcd#311]
At the moment resource `vcd_vapp_vm`supports only adding independent disks. There are no options to handle VM disks (add them, resize them), but there may be such a need for altering VM disks and their sizes.

**Comment by buec011** [comment]
I know this issue 311 is for the implementation in `vcd_vapp_vm`. But if a developer implements the it, it may be good to have bug 257 in mind to define functions and code structure:
We would like to see this in the 2 resource approach suggested here:
https://github.com/terraform-providers/terraform-provider-vcd/issues/257

**Comment by buec011** [comment]
Our business requires vm snapshots now. Since this is not possible with independent/namend disks at the moment, we got a demand for this feature. Unlike named disks, an extra attachment resource does not make sence for vm disks, since you cannot create a vm disk without a vm.

But maybe it make sence to have the disk in its own resource anyway (maybe it is possible to move a vm disk to another vm in future and we want to avoid https://github.com/terraform-providers/terraform-provider-vcd/issues/206 for vm disks)

May I suggest the following example code?:

```
resource vcd_vm_disk {
   attachment = vcd_vapp_vm.web1.name
   size = 1024
   [...]
}
```
If VCD support a move of vm disks in future, we may change the attachment value and it will be translated in the "move vm disk" api call.

**Comment by lvirbalas** [comment]
@buec011 please explain more about your use case. Esp., what do you want to do with snapshots and Terraform VM disks.

CC: @Didainius

**Comment by buec011** [comment]
@lvirbalas 

With independent disks / named disks (we use VCD 10), it is not possible to create a snapshot

(in GUI: VM -> Actions -> Create Snapshot) 

![image](https://user-images.githubusercontent.com/38046041/68662047-53c7c880-053c-11ea-8f72-3a086100f301.png)

We use snapshots before we or a third party deploys a new application in the VM. I think this is a usual use case why you want to use this vSphere / VCD feature.

If you use VM disks, you can take your snapshot as usual.

We do not need create and delete snapshots via terraform yet. We use the GUI for this at the moment, because they will resist temporary only.

**Comment by lvirbalas** [comment]
@buec011 I see. Are you still using the independent disks and do you still need the attachment resource for them #257 ?

**Comment by buec011** [comment]
> @buec011 I see. Are you still using the independent disks and do you still need the attachment resource for them #257 ?

It is still requested, but the use of VM disks is more important due to the snapshot problem. 
The concept of independent disks is similar to Volumes in AWS / Cinder in Openstack / VHDs in Azure. So we still like it.
Our demand to use independent disk will rise (examples I can think of)
- if `VM` snapshots are possible, 
- if `volume snapshot` or `disk clones` of independent disks are possible, 
- if multi-attach is possible
- maybe if you can choose first class disks without shadow VM.

**Comment by vbauzysvmware** [comment]
Implemented in https://github.com/terraform-providers/terraform-provider-vcd/pull/412
