### ISSUE TITLE
vCloud Director Provider - No organization policy lease time options

### ISSUE THREAD

**Issue by sysadmintutorials** [terraform-providers/terraform-provider-vcd#385]
Hi,

I'm writing to ask for a feature request which is to add org policy lease options within the vcloud provider. 

### Terraform Version
Terraform v0.12.13
+ provider.vcd v2.5.0

### Affected Resource(s)
Resource: vcd_org

### Expected Behavior
Creating a new vcd_org, we should have an argument that allows us to specify the following:
- Maximum runtime lease
- Maximum storage lease
- Storage Cleanup

### Actual Behavior
Creating a new org sets the leases to default:
- Maximum runtime lease: 7 days
- Maximum storage lease: 30 days
- Storage cleanup: move to expired items

### Steps to Reproduce
1. terraform plan or apply does not give any options to specific lease times in Org creation or updates:

Terraform will perform the following actions:

  vcd_org.org-name will be updated in-place
  ~ resource "vcd_org" "org-name" {
        can_publish_catalogs         = false
        delay_after_power_on_seconds = 0
        delete_force                 = true
        delete_recursive             = true
        deployed_vm_quota            = 0
      ~ description                  = "Terraform Create Org" -> "Terraform1 Create Org"
        full_name                    = "My Terraform Organization"
        id                           = "urn:vcloud:org:ff1974f7-d893-4fd6-b129-531432ded60b"
        is_enabled                   = true
        name                         = "Terraform1"
        stored_vm_quota              = 0
    }

**Comment by vbauzysvmware** [comment]
Thank you for feature proposal.

**Comment by nilic** [comment]
I hate to leave a basically +1 post, but this is a very important feature for our use case. As a SP, we use Terraform for provisioning new tenants. Current provider covers 95% of our needs, but this is a setting which still requires manual workarounds for each and every tenant, since the default Org lease values are useless for everything except trial tenants (and even for them it would be useful to be able to define lease times, because the default runtime value of 7 days is too short).

**Comment by dataclouder** [comment]
The feature is under review in PR #432
Please have a look, try it, and comment on the implementation.

**Comment by dataclouder** [comment]
Implemented in PR #432, now merged to master
