### ISSUE TITLE
Actual file size does not match metadata size

### ISSUE THREAD

**Issue by rhysjtevans** [terraform-providers/terraform-provider-vcd#424]
https://github.com/terraform-providers/terraform-provider-vcd/blob/bea14a76ffd413cf1c98f94e2c2d32b783d42f7f/vendor/github.com/vmware/go-vcloud-director/v2/govcd/catalog.go#L573

Is this by design? I've created an ova file using Packer/vagrant and have it successfully exported.
No error in the log file go vcd log.

OVF states it is 80GB disk but the actual vmdk is thinly provisioned and whitespace zero'd out so is actually < 1GB.

virtualbox exports the vmdk file compressed, any workaround/suggestions?

**Comment by vbauzysvmware** [comment]
Hi @rhysjtevans - Yes, it was by design. Yet this seems won't work with thin provisioned disks. At the moment(until we make the change) workaround would be export OVF with none thinly provisioned disks, by inflating them before export. https://docs.vmware.com/en/VMware-vSphere/6.7/com.vmware.vsphere.storage.doc/GUID-C371B88F-C407-4A69-8F3B-FA877D6955F8.html

**Comment by vbauzysvmware** [comment]
Hi @rhysjtevans 
I tested OVA thin provisioned and exported from vCD and it works fine. I am interested in your builded OVA file. Could you share for us to try?

**Comment by rhysjtevans** [comment]
Sorry @vbauzysvmware  not managed to get back to this yet.

**Comment by vbauzysvmware** [comment]
Please reopen when more information provided.
