### ISSUE TITLE
self.ip in provisioner returns allocated

### ISSUE THREAD

**Issue by harmjanblok** [terraform-providers/terraform-provider-vcd#50]
Hello,

I'm using the variable `${self.ip}` in a provisioner, the server uses DHCP to get it's address. In the previous terraform version `0.9.8` I didn't specify the `ip` argument as part of the `vcd_vapp`. However the IP isn't available anymore during the provisioning phase.

### Terraform Version
- terraform v0.10.2
- terraform-provider-vcd from 2b6e626

### Affected Resource(s)
- vcd_vapp

### Terraform Configuration Files
```hcl
resource "vcd_vapp" "worker_a" {
  catalog_name = "foo"
  cpus = 12
  count = 2
  initscript = "echo 'set ComputerName'"
  memory = 32768
  name = "worker-${element(split("-", uuid()), 0)}"
  network_name = "PRODUCTION-workers"
  provider = "vcd.ZONE-A"
  template_name = "foo-0.0.8"
}

provisioner "local-exec" {
  command = "echo '${self.ip}'"
}
```

### Expected Behavior
Echo's the DHCP assigned IP address of the `vapp`.

### Actual Behavior
Echo's `allocated`.

**Comment by harmjanblok** [comment]
When I configure the `ip` argument and set it to `dhcp` it returns the actual IP during provisioning.

```hcl
resource "vcd_vapp" "worker_a" {
  catalog_name = "foo"
  cpus = 12
  count = 2
  initscript = "echo 'set ComputerName'"
  ip = "dhcp"
  memory = 32768
  name = "worker-${element(split("-", uuid()), 0)}"
  network_name = "PRODUCTION-workers"
  provider = "vcd.ZONE-A"
  template_name = "foo-0.0.8"
}
```

**Comment by bobbydeveaux** [comment]
Potential fix needed around the else statement here:


```
if _, ok := d.GetOk("ip"); ok {
		ip := "allocated"

		oldIp, newIp := d.GetChange("ip")

		log.Printf("[DEBUG] IP has changes, old: %s - new: %s", oldIp, newIp)

		if newIp != "allocated" {
			log.Printf("[DEBUG] IP is assigned. Lets get it (%s)", d.Get("ip"))
			ip, err = getVAppIPAddress(d, meta)
			if err != nil {
				return err
			}
		} else {
			log.Printf("[DEBUG] IP is 'allocated'")
		}

		d.Set("ip", ip)
	} else {
		d.Set("ip", "allocated")
	}

```

**Comment by kradalby** [comment]
@bobbydeveaux As we only use allocation I have a suggestion that takes a different approach.

Instead of trying to force everything into the `ip` variable, introduce a variable to select how the IP is acquired. 

An example implementation for just the virtual machine is here: 
https://github.com/kradalby/terraform-provider-vcd/commit/b6dadc5a4509cbf8e08474b6826fb6887db128b9

Introducing `ip_allocation_mode`, which should be dhcp or allocated. If set, it is passed to the `vm.ChangeNetworkConfig` function so it is handed correctly in the library. This allowes the IP variable to be set to an IP after computation, or statically.

The use case for this is to set DNS entries after the IP is computed.

I have not battle tested my solution, and it was mostly proof of concept. The name can also be changed, and it should be implemented in vApp aswell.

Also, should the `ip` variable be named so it can distinct ipv4 and ipv6?

Thoughts on the approach?

**Comment by kradalby** [comment]
I'm bumping this one, any thoughts? I would not mind implementing it, as i need it and currently use my own fork to get this functionality. However, it should probably be done after, or in conjunction with #59.

**Comment by bobbydeveaux** [comment]
#59 is a pain

Completely agree with this idea though. Great suggestion.

No harm in branching from master for an initial stab at this :)

**Comment by kradalby** [comment]
I'll have a look at this later this week, try to get a proper grasp at #59 in addition to see that I don't make any  double work. We need that patch as well in the long run.

**Comment by Didainius** [comment]
I'm closing this as the new networks functionality coming with #177 will solve the issues.
