### ISSUE TITLE
Guest customization for a vApp doesn't work because it's enabled after first power-on

### ISSUE THREAD

**Issue by pasikarkkainen** [terraform-providers/terraform-provider-vcd#62]
While testing the current master branch of terraform-provider-vcd I noticed guest customization for a new vApp is executed/enabled *after* vApp power-on, which doesn't work, because guest customization needs to be enabled *before* first power-on, so it can actually be executed by vcloud director / vmware-tools.

Or is there something I'm missing? Otherwise I'll submit a pull request soon to fix this.

**Comment by opsforge** [comment]
Using v1.0.0 (not current master) I can say I've always used `power_on: true` and `initscript` worked fine for me on all runs. The exception to this is when you don't have an IP address or the address is in use in a fully consumed network pool. In those cases the provider doesn't error, but times out waiting for the pool to give you an IP address.

However from what I've seen in those cases the machine remains powered off, so you could still run an initscript post manually (at least I've done that and it worked).

Where do you see the behaviour for the initscript changing in the diff on master @pasikarkkainen ?

**Comment by opsforge** [comment]
To elaborate further I think what we're looking at here is https://github.com/terraform-providers/terraform-provider-vcd/blob/33928bc0817a1897c685ce898f74d91e948f32e7/vcd/resource_vcd_vapp_vm.go#L193 triggering https://github.com/UKCloud/govcloudair/blob/4cfe129e03c2911cf91371baf11e182b164695b0/vapp.go#L535 and that results in a state of enabled always true. Because of that regardless the scenario, the guest customization will run on next power on: https://pubs.vmware.com/vca/index.jsp?topic=%2Fcom.vmware.vcloud.api.reference.doc_56%2Fdoc%2Flanding-user_operations.html

At least this would explain the behavior I experienced - let me know if you encountered otherwise.

**Comment by pasikarkkainen** [comment]
I tested the current vmware-takes-ownership branch, and guest customization is still broken. It fails every single time I try to provision a new vApp. In current version it's still enabled *after* the vApp power-on, which won't work. So currently one has to manually run another power-off/power-on cycle for the new vApp, and *then* the guest customization is executed. This isn't ideal.

So guest customization needs to be enabled *before* the first vApp power-on, so it actually gets executed as part of the normal vApp/VM provisioning process and works automatically.

I'll prepare another PR soon against the latest version in vmware-takes-ownership branch.

**Comment by pasikarkkainen** [comment]
New PR against the 'vmware-takes-ownership' branch here:
https://github.com/terraform-providers/terraform-provider-vcd/pull/119

**Comment by lvirbalas** [comment]
Fix (PR #119) merged into vmware-takes-ownership branch.
